name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4.2.0
        with: 
          node-version: "18.17.x"
      - name: install deps
        run: npm install
      - name: run app
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./dist
    
